name: "S3 List Object with Tag"

description: "An action that searches for objects in a s3 bucket with a specific tag (key/value)"

inputs:
  aws_region:
    description: "The AWS region where the S3 bucket resides."
    required: true
  aws_access_key_id:
    description: "The AWS access key ID for authentication."
    required: true
  aws_secret_access_key:
    description: "The AWS secret access key for authentication."
    required: true
  bucket_name:
    description: "The name of the S3 bucket to search within."
    required: true
  tag_key:
    description: "The key of the tag to search for on S3 objects."
    required: true
  tag_value:
    description: "The value of the tag to match on S3 objects."
    required: true

outputs:
  objects:
    description: "JSON list of objects with the specified tag"

runs:
  using: "docker"
  image: "docker://ghcr.io/wigertztech/action-s3-list-objects-with-tag:latest"
  entrypoint: "node"
  args: ["/app/dist/index.js"]
  env:
    AWS_REGION: ${{ inputs.aws_region }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
    BUCKET_NAME: ${{ inputs.bucket_name }}
    TAG_KEY: ${{ inputs.tag_key }}
    TAG_VALUE: ${{ inputs.tag_value }}
